# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.wait = WebDriverWait(self.driver, 10)  # 10 seconds timeout
    self.vars = {}
  def teardown_method(self, method):
    self.driver.quit()
  def test_login(self):
    self.driver.get("../login/login.php")
    self.driver.set_window_size(1060, 804)
    self.wait.until(EC.visibility_of_element_located((By.ID, "email"))).send_keys("farmfoliomini@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("Admin@2004")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(5)").click()
    self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".logout-btn"))).click()
    self.wait.until(EC.visibility_of_element_located((By.ID, "email")))
    self.driver.find_element(By.ID, "email").send_keys("rohithreghu482@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("Abin@2004")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(5)").click()
    self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".popup-logout-btn"))).click()
    assert self.wait.until(EC.visibility_of_element_located((By.ID, "email"))), "Test Passed"
