# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPayment():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_payment(self):
    self.driver.get("../login/login.php")
    self.driver.set_window_size(1057, 803)
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("rohithreghu482@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Abin@2004")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(5)").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".result-card:nth-child(4) .add-to-cart-btn").click()
    assert self.driver.switch_to.alert.text == "Product added to cart!"
    self.driver.find_element(By.LINK_TEXT, "My Cart").click()
    self.driver.find_element(By.CSS_SELECTOR, ".checkout-btn").click()
    self.driver.find_element(By.ID, "online").click()
    self.driver.find_element(By.ID, "house_name").click()
    self.driver.find_element(By.ID, "house_name").send_keys("Rohith")
    self.driver.find_element(By.ID, "post_office").click()
    self.driver.find_element(By.ID, "post_office").send_keys("Kavumbhagom")
    self.driver.find_element(By.ID, "place").click()
    self.driver.find_element(By.ID, "place").send_keys("kottayam")
    self.driver.find_element(By.ID, "pin").click()
    self.driver.find_element(By.ID, "pin").click()
    self.driver.find_element(By.ID, "pin").send_keys("686519")
    self.driver.find_element(By.ID, "phone").click()
    self.driver.find_element(By.ID, "phone").send_keys("8590177602")
    self.driver.find_element(By.CSS_SELECTOR, ".form-grid").click()
    self.driver.find_element(By.NAME, "place_order").click()
    assert self.driver.switch_to.alert.text == "Error processing payment. Please try again."
    self.driver.find_element(By.NAME, "place_order").click()
    assert self.driver.switch_to.alert.text == "Error processing payment. Please try again."
    self.driver.find_element(By.NAME, "place_order").click()
    assert self.driver.switch_to.alert.text == "Error processing payment. Please try again."
    self.driver.find_element(By.NAME, "place_order").click()
    assert self.driver.switch_to.alert.text == "Error processing payment. Please try again."
    self.driver.find_element(By.NAME, "place_order").click()
    assert self.driver.switch_to.alert.text == "Error processing payment. Please try again."
    self.driver.find_element(By.NAME, "place_order").click()
    assert self.driver.switch_to.alert.text == "Error processing payment. Please try again."
    self.driver.find_element(By.CSS_SELECTOR, ".payment-option:nth-child(2) > label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fa-money-bill-wave").click()
    self.driver.find_element(By.NAME, "place_order").click()
    self.driver.find_element(By.LINK_TEXT, "View Orders").click()
  
