# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSearch():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_search(self):
    self.driver.get("http://localhost/mini%20project/login/login.php")
    self.driver.set_window_size(1060, 804)
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("rohithreghu842@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Hari@2004")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(5)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".logout-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2)").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("rohithreghu482@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Abin@2004")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(5)").click()
    self.driver.find_element(By.LINK_TEXT, "Browse Farms").click()
    self.driver.find_element(By.ID, "searchInput").click()
    self.driver.find_element(By.ID, "searchInput").send_keys("eggs")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(3)").click()
    self.driver.find_element(By.ID, "searchInput").click()
    self.driver.find_element(By.ID, "searchInput").send_keys("mango")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(3)").click()
    self.driver.find_element(By.ID, "searchInput").click()
    self.driver.find_element(By.ID, "searchInput").send_keys("selam ")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(3)").click()
  
