# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestReview():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_review(self):
    self.driver.get("http://localhost/mini%20project/login/login.php")
    self.driver.set_window_size(1057, 803)
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("v7349603@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Rohith@2004")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(5)").click()
    self.driver.find_element(By.LINK_TEXT, "View Farm").click()
    self.driver.find_element(By.CSS_SELECTOR, "#starRating > .fa-star:nth-child(4)").click()
    self.driver.find_element(By.ID, "reviewComment").click()
    self.driver.find_element(By.ID, "reviewComment").send_keys("good farm")
    self.driver.find_element(By.CSS_SELECTOR, ".submit-review").click()
    assert self.driver.switch_to.alert.text == "Review submitted successfully"
    self.driver.find_element(By.ID, "reviewComment").click()
    self.driver.find_element(By.ID, "reviewComment").send_keys("good ")
    self.driver.find_element(By.CSS_SELECTOR, ".submit-review").click()
    assert self.driver.switch_to.alert.text == "Review updated successfully"
  
