# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCategory():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_category(self):
    self.driver.get("http://localhost/mini%20project/login/login.php")
    self.driver.set_window_size(1058, 804)
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("farmfoliomin@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Admin@2004")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(5)").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("farmfoliomini@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Admin@2004")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(5)").click()
    self.driver.find_element(By.ID, "category").click()
    self.driver.find_element(By.ID, "category").click()
    self.driver.find_element(By.ID, "category").send_keys("fruits")
    self.driver.find_element(By.ID, "subcategory").click()
    self.driver.find_element(By.ID, "subcategory").send_keys("mango")
    self.driver.find_element(By.NAME, "add_category").click()
    self.driver.find_element(By.CSS_SELECTOR, ".logout-btn").click()
    self.driver.close()
  
